[workspace]

resolver = "2"

members = [
    "games/1-first-try", 
    "games/2-first-render"
]

[workspace.dependencies]
bevy = "0.15.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

